OasX/Models/Simulation/SimulationInspectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace OasX.Models.Simulation
{
    public class SimulationInspectViewModel
    {
        private Domain.Service.Paper paper;
        private SimulationInputModel model;

        public SimulationInspectViewModel(Domain.Service.Paper paper, SimulationInputModel model) {
            SingleQuestions = new List<SingleQuestionInspect>();
            MultipleQuestions = new List<MultipleQuestionInspect>();
            SubjectiveQuestions = new List<SubjectiveQuestionInspect>();

            foreach (var q in paper.SingleQuestions) {
                var a = model.SingleQuestions.FirstOrDefault(s => s.QuestionId == q.QuestionId);
                var single = new SingleQuestionInspect
                {
                    QuestionId = q.QuestionId,
                    Body = q.Body,
                    Score = q.Score,
                    Options = q.Options.Select(o => new QuestionOptionInspect
                    {
                        OptionId = o.OptionId, IsRight = o.IsRight, Content = o.Content
                    }).ToList()
                };

                if (a != null && a.CheckedOption.HasValue) {
                    var checkedOption = single.Options.FirstOrDefault(o => o.OptionId == a.CheckedOption.Value);
                    if (checkedOption != null) {
                        checkedOption.Checked = true;
                    }
                }

                if (a == null) {
                    single.GotScore = 0;
                } else {
                    single.GotScore = single.Options.FirstOrDefault(o => o.OptionId == a.CheckedOption.Value).IsRight
                        ? single.Score
                        : 0;
                }

                SingleQuestions.Add(single);
            }
            foreach (var q in paper.MultipleQuestions) {
                var a = model.MultipleQuestions.FirstOrDefault(s => s.QuestionId == q.QuestionId);
                var multiple = new MultipleQuestionInspect
                {
                    QuestionId = q.QuestionId,
                    Body = q.Body,
                    Score = q.Score,
                    Options = q.Options.Select(o => new QuestionOptionInspect
                    {
                        OptionId = o.OptionId, IsRight = o.IsRight, Content = o.Content
                    }).ToList()
                };

                if (a != null) {
                    foreach (var co in a.CheckedOptions) {
                        var checkedOption = multiple.Options.FirstOrDefault(o => o.OptionId == co.OptionId);
                        if (checkedOption != null) {
                            checkedOption.Checked = co.Checked;
                        }
                    }
                }

                if (a == null) {
                    multiple.GotScore = 0;
                } else {
                    bool isAllRight = true;
                    foreach (var co in a.CheckedOptions) {
                        if (!multiple.Options.FirstOrDefault(o => o.OptionId == co.OptionId).IsRight) {
                            isAllRight = false;
                            break;
                        }
                    }
                    multiple.GotScore = isAllRight
                        ? multiple.Score
                        : 0;
                }

                MultipleQuestions.Add(multiple);
            }
            foreach (var q in paper.SubjectiveQuestions) {
                var a = model.SubjectiveQuestions.FirstOrDefault(s => s.QuestionId == q.QuestionId);
                var subjective = new SubjectiveQuestionInspect
                {
                    QuestionId = q.QuestionId,
                    Body = q.Body,
                    Score = q.Score,
                    Answer = q.Answer
                };
                if (a != null) {
                    subjective.WriteDown = a.WriteDown;
                }

                SubjectiveQuestions.Add(subjective);
            }
        }

        public List<SingleQuestionInspect> SingleQuestions { get; set; }
        public List<MultipleQuestionInspect> MultipleQuestions { get; set; }
        public List<SubjectiveQuestionInspect> SubjectiveQuestions { get; set; }
    }

    public class SingleQuestionInspect
    {
        public Guid QuestionId { get; set; }
        public string Body { get; set; }
        public int Score { get; set; }
        public int GotScore { get; set; }
        public List<QuestionOptionInspect> Options { get; set; }
    }

    public class MultipleQuestionInspect
    {
        public Guid QuestionId { get; set; }
        public string Body { get; set; }
        public int Score { get; set; }
        public int GotScore { get; set; }
        public List<QuestionOptionInspect> Options { get; set; }
    }

    public class QuestionOptionInspect
    {
        public Guid OptionId { get; set; }
        public string Content { get; set; }
        public bool Checked { get; set; }
        public bool IsRight { get; set; }
    }

    public class SubjectiveQuestionInspect
    {
        public Guid QuestionId { get; set; }
        public string Answer { get; set; }
        public string WriteDown { get; set; }

        public int Score { get; set; }
        public string Body { get; set; }
    }
}

OasX/Models/Simulation/SimulationViewModel.cs
using System;
using System.Collections.Generic;

namespace OasX.Models.Simulation
{
    public class SimulationInputModel
    {
        public List<SingleQuestion> SingleQuestions { get; set; }
        public List<MultipleQuestion> MultipleQuestions { get; set; }
        public List<SubjectiveQuestion> SubjectiveQuestions { get; set; }
    }

    public class SingleQuestion
    {
        public Guid QuestionId { get; set; }
        public string Body { get; set; }
        public Guid? CheckedOption { get; set; }
    }

    public class MultipleQuestion
    {
        public Guid QuestionId { get; set; }
        public string Body { get; set; }
        public List<QuestionOption> CheckedOptions { get; set; }
    }

    public class QuestionOption
    {
        public Guid OptionId { get; set; }
        public bool Checked { get; set; }
    }

    public class SubjectiveQuestion
    {
        public Guid QuestionId { get; set; }
        public string WriteDown { get; set; }
    }
}

OasX/Controllers/SimulationController.cs
using System;
using System.Web.Mvc;
using OasX.Domain.Service;
using OasX.Models.Simulation;
using OasX.Service.Interfaces;

namespace OasX.Controllers
{
    public class SimulationController : Controller
    {
        private const string Paper = "CurrentPaper";
        private ISimulationService _simulationService;
        private IQuestionService _questionService;

        public SimulationController(ISimulationService simulationService, IQuestionService questionService) {
            _simulationService = simulationService;
            _questionService = questionService;
        }

        public ActionResult Index(string courseId) {
            return View();
        }

        public ActionResult StartNew(string courseId, string style) {
            var paper = _simulationService.GeneratePaper(courseId, style);
            Session[Paper] = paper;
            return View(paper);
        }

        public ActionResult Submit(string courseId, SimulationInputModel model) {
            var paper = (Paper) Session[Paper];
            var viewModel = new SimulationInspectViewModel(paper, model);
            TempData["Inspect"] = viewModel;
            Session[Paper] = null;
            return RedirectToAction("Inspect");
        }

        public ActionResult Inspect(string courseId) {
            var viewModel = (SimulationInspectViewModel) TempData["Inspect"];
            return View(viewModel);
        }

        public ActionResult DownloadAttachment(Guid questionId) {
            var question = _questionService.GetSubjectiveQuestion(questionId);
            return File(question.AttachmentPath, @"application/octet-stream", question.AttachmentName);
        }
    }
}

OasX/Views/Simulation/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>选择试卷形式</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <h3>实操题考试</h3>
                    <p>一体化地考试形式，将理论融入实际操作中</p>
                    <p>@Html.ActionLink("开始", "StartNew", new {style = "Random"})</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <h3>理论题考试</h3>
                    <p>理论知识考试</p>
                    <p>@Html.ActionLink("开始", "StartNew", new {style = "Simple"})</p>
                </div>
            </div>
        </div>
    </div>
</div>

OasX/Views/Simulation/Inspect.cshtml
@model OasX.Models.Simulation.SimulationInspectViewModel
@{
    ViewBag.Title = "Inspect";
}

@if (Model.SingleQuestions.Any()) {
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">单选题</h3>
            </div>
            <div class="panel-body">
                @for (int i = 0; i < Model.SingleQuestions.Count; i++) {
                    if (i != 0) {
                        <hr />
                    }

                    var question = Model.SingleQuestions[i];
                    <p>@question.Body (@question.Score 分)</p>
                    <p>您的得分: @question.GotScore</p>
                    for (int o = 0; o < question.Options.Count; o++) {
                        var option = question.Options.ElementAt(o);
                        <div class="radio disabled">
                            <label>
                                <input type="radio" disabled name="SingleQuestions[@i].CheckedOption" value="@option.OptionId" @{
                                                                                                                                   if (option.Checked) {
                                                                                                                                       Write("checked=\"checked\"");
                                                                                                                                   }
                                                                                                                               } />
                                @option.Content @if (option.IsRight) {
                                                    if (option.Checked) {
                                                        <span class="glyphicon glyphicon-ok"></span>
                                                    } else {
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    }
                                                } else {
                                                    if (option.Checked) {
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    }
                                                }
                            </label>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
}

@if (Model.MultipleQuestions.Any()) {
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">多选题</h3>
            </div>
            <div class="panel-body">
                @for (int i = 0; i < Model.MultipleQuestions.Count; i++) {
                    if (i != 0) {
                        <hr />
                    }

                    var question = Model.MultipleQuestions[i];
                    <p>@question.Body (@question.Score 分)</p>
                    <p>您的得分: @question.GotScore</p>
                    for (int o = 0; o < question.Options.Count; o++) {
                        var option = question.Options.ElementAt(o);
                        <div class="checkbox disabled">
                            <label>
                                <input type="checkbox" disabled name="MultipleQuestions[@i].CheckedOptions[@o].Checked" value="true" @{
                                                                                                                                         if (option.Checked) {
                                                                                                                                             Write("checked=\"checked\"");
                                                                                                                                         }
                                                                                                                                     } />

                                @option.Content @if (option.IsRight) {
                                                    if (option.Checked) {
                                                        <span class="glyphicon glyphicon-ok"></span>
                                                    } else {
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    }
                                                } else {
                                                    if (option.Checked) {
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    }
                                                }
                            </label>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
}

@if (Model.SubjectiveQuestions.Any()) {
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">主观题</h3>
            </div>
            <div class="panel-body">
                @for (int i = 0; i < Model.SubjectiveQuestions.Count; i++) {
                    var question = Model.SubjectiveQuestions[i];
                    <p>@question.Body (@question.Score 分)</p>
                    @Html.TextArea("SubjectiveQuestions[" + i + "].WriteDown", question.WriteDown, new {@class = "form-control", rows = 5, disabled = ""})
                    <p>参考答案: @question.Answer</p>
                }
            </div>
        </div>
    </div>
}

OasX/Views/Simulation/StartNew.cshtml
@model OasX.Domain.Service.Paper
@{
    ViewBag.Title = "StartNew";
}

@if (Model.SingleQuestions.Any() || Model.MultipleQuestions.Any() || Model.SubjectiveQuestions.Any()) {
    using (Html.BeginForm("Submit", "Simulation", FormMethod.Post, new {@class = "form-horizontal"})) {
        if (Model.SingleQuestions.Any()) {
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">单选题</h3>
                    </div>
                    <div class="panel-body">
                        @for (int i = 0; i < Model.SingleQuestions.Count; i++) {
                            if (i != 0) {
                                <hr/>
                            }

                            var question = Model.SingleQuestions[i];
                            @Html.Hidden("SingleQuestions[" + i + "].QuestionId", question.QuestionId)
                            <p>@question.Body (@question.Score 分)</p>

                            for (int o = 0; o < question.Options.Count; o++) {
                                var option = question.Options.ElementAt(o);
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="SingleQuestions[@i].CheckedOption" value="@option.OptionId" />
                                        @option.Content
                                    </label>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        }

        if (Model.MultipleQuestions.Any()) {
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">多选题</h3>
                    </div>
                    <div class="panel-body">
                        @for (int i = 0; i < Model.MultipleQuestions.Count; i++) {
                            if (i != 0) {
                                <hr />
                            }

                            var question = Model.MultipleQuestions[i];
                            @Html.Hidden("MultipleQuestions[" + i + "].QuestionId", question.QuestionId)
                            <p>@question.Body (@question.Score 分)</p>

                            for (int o = 0; o < question.Options.Count; o++) {
                                var option = question.Options.ElementAt(o);
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="MultipleQuestions[@i].CheckedOptions[@o].Checked" value="true" />
                                        @option.Content
                                        <input type="hidden" name="MultipleQuestions[@i].CheckedOptions[@o].Checked" value="false" />
                                        <input type="hidden" name="MultipleQuestions[@i].CheckedOptions[@o].OptionId" value="@option.OptionId" />
                                    </label>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        }

        if (Model.SubjectiveQuestions.Any()) {
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">主观题</h3>
                    </div>
                    <div class="panel-body">
                        @for (int i = 0; i < Model.SubjectiveQuestions.Count; i++) {
                            var question = Model.SubjectiveQuestions[i];
                            @Html.Hidden("SubjectiveQuestions[" + i + "].QuestionId", question.QuestionId)
                            <p>@question.Body (@question.Score 分)</p>
                            if (!string.IsNullOrEmpty(question.AttachmentPath) && !string.IsNullOrEmpty(question.AttachmentName)) {
                                <p>附件: <a href="@Url.Action("DownloadAttachment", new {questionId = question.QuestionId})">@question.AttachmentName</a></p>
                            }
                            @Html.TextArea("SubjectiveQuestions[" + i + "].WriteDown", new {@class = "form-control", rows = 5})
                        }
                    </div>
                </div>
            </div>
        }
        <input type="submit" class="btn btn-primary" value="提交" />
    }
} else {
    <p>没有试题可供生成试卷</p>
}